image:
  - Visual Studio 2019

cache:
  - c:\users\appveyor\clcache
  - c:\local\boost_1_69_0

environment:
  BOOST_ROOT: C:\local\boost_1_69_0
  BOOST_LIBRARYDIR: C:\local\boost_1_69_0\lib64-msvc-14

init:
  - set PATH=c:\Python37;c:\Python37\Scripts;%PATH%
  - pip install clcache

before_build:
  - clcache -s

install:
  - ps: Write-Host "Checking for Boost 1.69.0 x64...";$boostdir  = Test-Path $Env:BOOST_ROOT;If ($boostdir -eq $False) {Write-Host "Downloading Boost 1.69.0 x64...";$exePath = "$Env:TEMP\boost_1_69_0-msvc-14.1-64.exe";(New-Object Net.WebClient).DownloadFile('https://bintray.com/boostorg/release/download_file?file_path=1.69.0%2Fbinaries%2Fboost_1_69_0-msvc-14.1-64.exe', $exePath);Write-Host "Installing Boost 1.69.0 x64...";cmd /c start /wait "$exePath" /verysilent;del $exePath};Write-Host "Boost 1.69.0 x64 installed!" -ForegroundColor Green

build_script:
  - md build
  - cd build
  - cmake -G "Visual Studio 16 2019" -A x64 .. -DARCH=default -DOPENSSL_ROOT_DIR=C:\OpenSSL-v111-Win64
  - MSBuild Qbit.sln /p:CLToolExe=clcache.exe /p:CLToolPath=c:\Python37\Scripts\ /p:Configuration=Release /m
  - src\Release\cryptotest.exe

after_build:
  - clcache -s
  - if not defined APPVEYOR_REPO_TAG_NAME (set APPVEYOR_REPO_TAG_NAME=%APPVEYOR_REPO_COMMIT%)
  - cd src\Release
  - mkdir Qbit-%APPVEYOR_REPO_TAG_NAME%
  - copy *.exe Qbit-%APPVEYOR_REPO_TAG_NAME%
  - copy ..\..\..\LICENSE Qbit-%APPVEYOR_REPO_TAG_NAME%
  - 7z a Qbit-%APPVEYOR_REPO_TAG_NAME%-windows.zip turtlecoin-%APPVEYOR_REPO_TAG_NAME%
  - copy Qbit-%APPVEYOR_REPO_TAG_NAME%-windows.zip ..\..\..\

artifacts:
  - path: Qbit-$(APPVEYOR_REPO_TAG_NAME)-windows.zip
    name: QbitRelease

deploy:
  - provider: GitHub
    auth_token:
      secure: 
    artifact: QbitRelease
    draft: false
    prerelease: false
    on:
      appveyor_repo_name: QbitNetwork/Qbit
      appveyor_repo_tag: true

  - provider: S3
    access_key_id:
      secure:  0280f348f6644b1cb8e7c2a9a4409fba
    secret_access_key:
      secure: d6306d05-811a-4e47-b96f-350afe2f6faf
    bucket: qbit
    region: European Union
    set_public: true
    folder: Qbit
    artifact: QbitRelease
    on:
      appveyor_repo_name: QbitNetwork/Qbit
